### ISSUE TITLE
UserAgent  is disconnected from Websocket connection with 1006(inactivity_timeout is set to 0)

### ISSUE THREAD

**Issue by darrenli912** [mojolicious/mojo#1498] opened 2020-04-22 09:54 UTC
* Mojolicious version: 8.38
* Perl version: v5.26.1
* Operating system: ubuntu 18.04

### Steps to reproduce the behavior
Hello, 
I test  ua connect websockt server.
I have set the inactivity_timeout  ,but ua   disconnects in several second with 1006 code. 

My server script:
use Mojolicious::Lite;
use Mojo::EventEmitter;

helper events => sub { state $events = Mojo::EventEmitter->new };

websocket '/echo' => sub {
  my $c = shift;

  $c->inactivity_timeout(3600);

  $c->on(message => sub { shift->events->emit(mojochat => shift) });

  my $cb = $c->events->on(mojochat => sub { $c->send(pop) });
  $c->on(finish => sub { shift->events->unsubscribe(mojochat => $cb) });
};

app->start;

My client script:
use Mojo::UserAgent;
use Mojo::IOLoop;
use Mojo::Base -strict;

sub ws_connect {

  state $ua;

  say "Connecting..";
  $ua = Mojo::UserAgent->new;
  $ua->inactivity_timeout(0);

  $ua->websocket('ws://127.0.0.1:3000/echo' => \&onConnect);

}

sub onConnect {
  my ($ua, $tx) = @_;

  if (!$tx->is_websocket) {
        say 'WebSocket handshake failed!';
  }
  say "Connected!";

  $tx->on(finish => sub {
        my ($tx, $code) = @_;
        say "WebSocket closed with status $code";
  });

}

ws_connect();
Mojo::IOLoop->start;

### Expected behavior
ua can connect to server.
### Actual behavior
 ua quit with 1006  in several seconds.

**Comment by elcamlost** [comment] 2020-04-23 11:42
@darrenli912 I guess, issue is fixed in Mojolicious 8.40. At least, I can't reproduce it after upgrade.

**Comment by kraih** [comment] 2020-04-23 11:57
I'm going to assume this is fixed. In the future please format issues with GitHub markup.

**Closed by kraih** 2020-04-23 11:57 UTC
