### ISSUE TITLE
Mojo::File::move_to fails when moving dir to dir

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1395] opened 2019-08-01 20:04 UTC
* Mojolicious version: 8.22
* Perl version: 5.30.0
* Operating system: CentOS Linux release 7.5.1804 (Core) 

I'm not sure if this is expected behavior or not, but this code:

```
my $mojo_dir = path('/path/to/dir');
$mojo_dir->move_to('/some/other/dir');
```

Fails with this error:

`Can't move file "/path/to/dir" to "/some/other/dir": Is a directory `

Which does not behave the same way as linux `mv`, but does behave like [File::Copy](https://metacpan.org/pod/File::Copy). Is this the expected behavior? The way to get the behavior of `mv` is:

`$mojo_dir->move_to('/some/other/dir', $mojo_dir->basename);`

My question is, is the above something that Mojo::File should handle with a `-d` check and add the basename, or is this working as intended and it's the user's responsibility to add that?

**Comment by Grinnz** [comment] 2019-08-01 20:14
It seems to be intended behavior of File::Copy which it is documented as delegating to, that it only copies into a target directory if the source is not a directory. See also this huge discussion about a similar function in Path::Tiny, which currently still uses the rename builtin: https://github.com/dagolden/Path-Tiny/pull/22

**Comment by srchulo** [comment] 2019-08-01 22:51
Yeah, it's fair to point out that it is documented as delegating to File::Copy, which behaves that way. Then I guess my question would be is that the correct/natural behavior? 

In my case, I'm trying to move all of the files in a directory (including directories) to another directory. Maybe there's a better way to do it than this, but here is what I had:

```
path($dir)->list({dir => 1})->each(sub ($mojo_file, $) {
    $mojo_file->move_to($new_dir);
});
```

Which now has to be something like:

```
path($dir)->list({dir => 1})->each(sub ($mojo_file, $) {
    if (-d $mojo_file) {
        $mojo_file->move_to(path($new_dir, $mojo_file->basename));
    } else {
        $mojo_file->move_to($new_dir);
    }
});
```

To me this seems confusing/unnatural because I have to think about whether the file is a directory or not, when really I just want the same behavior regardless. It seems strange to me that there are two different behaviors.

**Comment by srchulo** [comment] 2019-08-01 22:53
Although, I guess I should point out that I could just always do the directory case and that works for directories and files:

```
path($dir)->list({dir => 1})->each(sub ($mojo_file, $) {
    $mojo_file->move_to(path($new_dir, $mojo_file->basename));
});
```

**Comment by kraih** [comment] 2020-06-14 15:37
Since there have been no more updates to this issue i'm goig to close it as a `wontfix`. Because we just delegate to `File::Copy` and any fixes would have to go there.

**Closed by kraih** 2020-06-14 15:37 UTC
