### ISSUE TITLE
Growing Documentation has broken login.t example

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1421] opened 2019-10-09 15:05 UTC
* Mojolicious version: 8.25
* Perl version: 5.30
* Operating system: Ubuntu 18.04.2 LTS

### Steps to reproduce the behavior
Set up app shown [here](https://mojolicious.org/perldoc/Mojolicious/Guides/Growing#Testing) up to creating `login.t`. Then run the test:

```
prove -l t/login.t
```

### Expected behavior
All of the written tests should fail and produce output.

### Actual behavior
Instead, this error is given:

```
t/login.t .. Can't locate object method "dirname" via package "curfile" at t/login.t line 6.
```

I'm not sure if this means that anything else from 3665b710b45c67a7a704ce914810cac35cf224e1 is broken. It seems to be the only `require` usage, and most of the rest is tested code, so I think this may be it.

**Comment by Grinnz** [comment] 2019-10-09 15:06
Duplicate of https://github.com/mojolicious/mojo/pull/1417

**Comment by srchulo** [comment] 2019-10-09 15:08
@Grinnz my mistake. Should've checked existing issues first.

**Closed** 2019-10-09 15:10 UTC
